apostilas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path( 'adicionar_apostilas/', views.adicionar_apostilas, name='adicionar_apostilas'),
    path('apostila/<int:id>', views.apostila, name='apostila'),
    path('listar_tags/', views.listar_tags, name='listar_tags'),
    path('salvar_avaliacao/<int:id>/', views.salvar_avaliacao, name='salvar_avaliacao'),
]

study_async/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('flashcard/', include('flashcard.urls')),
    path('apostilas/', include('apostilas.urls')),
    path('', lambda requests: redirect('usuarios/logar/'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('cadastro/', views.cadastro, name='cadastro'),
     path('logar/', views.logar, name='logar'),
     path('logout/', views.logout, name='logout'),
]

apostilas/models.py
from django.db import models
from django.contrib.auth.models import User

class Tags(models.Model):
    nome = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nome

class Avaliacao(models.Model):
    valor = models.IntegerField()
    descricao = models.CharField(max_length=100)

    def __str__(self):
        return self.descricao

class Apostila(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=100)
    arquivo = models.FileField(upload_to='apostilas')
    tags = models.ManyToManyField(Tags)
    AVALIACAO_CHOICES = (
        ('5', 'Muito Bom'),
        ('4', 'Bom'),
        ('3', 'Regular'),
        ('2', 'Ruim'),
        ('1', 'Muito Ruim'),
    )
    avaliacao = models.CharField(max_length=1, choices=AVALIACAO_CHOICES, blank=True)

    def __str__(self):
        return self.titulo
    
    def lista_de_tags(self):
        return list(self.tags.all())
    
class ViewApostila(models.Model):
    ip = models.GenericIPAddressField()
    apostila = models.ForeignKey(Apostila, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.ip

apostilas/views.py
from django.shortcuts import render, redirect
from .models import Apostila, Tags, ViewApostila, Avaliacao
from django.db.models import Q
from django.contrib.messages import constants
from django.contrib import messages

def adicionar_apostilas(request):
    if request.method == 'GET':
        apostilas = Apostila.objects.filter(user=request.user)
        views_totais = ViewApostila.objects.filter(apostila__user = request.user).count()
        return render(request, 'adicionar_apostilas.html', {'apostilas': apostilas, 'views_totais': views_totais})
    elif request.method == 'POST':
        titulo = request.POST.get('titulo')
        arquivo = request.FILES['arquivo']

        apostila = Apostila(user=request.user, titulo=titulo, arquivo=arquivo)
        apostila.save()
        
        tags = request.POST.get('tags')
        list_tags = tags.split(',')
        
        for tag_name in list_tags:
            tag_existente = Tags.objects.filter(nome__iexact=tag_name).first()
            if not tag_existente:
                nova_tag = Tags(nome=tag_name)
                nova_tag.save()
                apostila.tags.add(nova_tag)
            else:
                apostila.tags.add(tag_existente)
        
        apostila.save()
        
        messages.add_message(
            request, constants.SUCCESS, 'Apostila adicionada com sucesso.'
        )
        return redirect('/apostilas/adicionar_apostilas/')

def apostila(request, id):
    apostila = Apostila.objects.get(id=id)
    view = ViewApostila(
        ip=request.META['REMOTE_ADDR'],
        apostila=apostila
    )
    view.save()
    views_unicas = ViewApostila.objects.filter(apostila=apostila).values('ip').distinct().count()
    views_totais = ViewApostila.objects.filter(apostila=apostila).count()

    avaliacoes = []
    for value, descricao in Apostila.AVALIACAO_CHOICES:
        avaliacoes.append({'id': value, 'descricao': descricao})

    return render(request, 'apostila.html', {'apostila': apostila, 'views_unicas': views_unicas, 'views_totais': views_totais, 'avaliacoes': avaliacoes})

def listar_tags(request):
    if request.method == 'GET':
        apostilas = Apostila.objects.filter(user=request.user)
        apostilas_filtradas = apostilas

        tag_filtrar = request.GET.get('tags')
        if tag_filtrar:
            tags = [tag.strip() for tag in tag_filtrar.split(',')]
            
            condicoes = Q()
            for tag in tags:
                condicoes |= Q(tags__nome__icontains=tag)
            apostilas_filtradas = apostilas_filtradas.filter(condicoes)

        return render(request, 'adicionar_apostilas.html', {'apostilas': apostilas, 'apostilas_filtradas': apostilas_filtradas})

def salvar_avaliacao(request, id):
    if request.method == 'POST':
        apostila = Apostila.objects.get(id=id)
        avaliacao_valor = request.POST.get('avaliacao')
        if avaliacao_valor:
            apostila.avaliacao = avaliacao_valor
            apostila.save()

    return redirect('apostila', id=id)

apostilas/templates/adicionar_apostilas.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}

    <link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/iniciar_desafio.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/desafio.css' %}" rel="stylesheet">
    <link href="{% static 'apostila/css/adicionar_apostilas.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'cabecalho' %}


{% block 'conteudo' %}
    {% include "partials/header.html" %}
    <div class="container">
        <br><br>
        <div class="row">
            <div class="col-md">
                <div class="box-form">
                    {% if messages %}
                        <br>
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
                            </section>
                        {% endfor %}
                        <br>
                    {% endif %}
                    <form action="{% url 'adicionar_apostilas' %}" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                        <p class="fonte-secundaria">Adicionar resumos</p>
                        <label for="titulo">Titulo</label>
                        <input type="text" name="titulo" id="titulo" class="form-control">
                        <br>
                        <label for="arquivo">Arquivo</label>
                        <input type="file" name="arquivo" id="arquivo" class="form-control">
                        <br>
                        <label for="tags">Tags(separadas por ,)</label>
                        <input type="text" name="tags" id="tags" class="form-control">
                        <br>
                        <input type="submit" class="btn-cadastro" value="Enviar">
                    </form>
                </div>
            </div>
            <div class="col-md">
                <div class="tabela-limitada">
                    <table class="tabela1">
                        <thead>
                        <tr>
                            <th scope="col">Titulo</th>
                            <th scope="col">Tag</th>
                            <th scope="col">Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for apostila in apostilas %}
                                <tr class="linha">
                                    <td>{{apostila.titulo}}</td>
                                    <td>{% for tag in apostila.lista_de_tags %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                                    <td><a href="{% url 'apostila' apostila.id %}" style="color: #fff; text-decoration: none;" class="btn-cadastro">Abrir</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <hr>
                <p class="fonte-secundaria">Views totais: {{views_totais}}</p>
            </div>
        </div>
        <hr>
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <div class="box-form">
                    <form action="{% url 'listar_tags' %}" method="GET" enctype='multipart/form-data'>
                        <p class="fonte-secundaria">Buscar resumos</p>
                        <label for="tags">Tags(separadas por ,)</label>
                        <input type="text" name="tags" id="tags" class="form-control">
                        <br>
                        <input type="submit" class="btn-cadastro" value="Buscar">
                    </form>
                </div>
            </div>
            <div class="col-md">
                <div class="tabela-limitada">
                    {% if apostilas_filtradas %}
                        <table id="tabela2">
                            <thead>
                            <tr>
                                <th scope="col">Titulo</th>
                                <th scope="col">Tag</th>
                                <th scope="col">Ação</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for apostila in apostilas_filtradas %}
                                    <tr class="linha">
                                        <td>{{apostila.titulo}}</td>
                                        <td>
                                            {% for tag in apostila.tags.all %}
                                                {{ tag.nome }}
                                                {% if not forloop.last %}, 
                                                {% endif %}
                                            {% endfor %}
                                        </td>
                                        <td><a href="{% url 'apostila' apostila.id %}" style="color: #fff; text-decoration: none;" class="btn-cadastro">Abrir</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock 'conteudo' %}

apostilas/templates/apostila.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}

    <link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/iniciar_desafio.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/desafio.css' %}" rel="stylesheet">
    <link href="{% static 'apostila/css/adicionar_apostilas.css' %}" rel="stylesheet">
    <link href="{% static 'apostila/css/apostila.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'cabecalho' %}


{% block 'conteudo' %}
    {% include "partials/header.html" %}
    <div class="container">
        <br><br>
        <div class="row">
            <div class="col-md">
                <p class="text_avaliacao" >{{apostila.titulo}}</p>
                <a href="{{apostila.arquivo.url}}">
                    <div style="width: 100%;" id="pdf-container"></div>
                </a>
            </div>
            <div class="col-md">
                <div class="d-flex justify-content-between">
                    <div>
                        <p>Views únicas: {{ views_unicas }}</p>
                        <p>Views totais: {{ views_totais }}</p>
                    </div>
                    <div class="d-flex flex-column align-items-center">
                        <p>
                            <strong class="text_avaliacao">Avaliação</strong>
                            {% if apostila.avaliacao %}
                               <p>{{ apostila.get_avaliacao_display }}</p>
                            {% else %}
                                <p>Sem avaliações</p>
                            {% endif %}
                        </p>
                    </div>
                </div>
                <hr>
                <p class="cabecario_avaliacao">Deixe sua avaliação</p>
                <form action="{% url 'salvar_avaliacao' apostila.id %}" method="POST">{% csrf_token %}
                    <select name="avaliacao" id="avaliacao" class="form-select2">
                        <option value="">Selecione uma avaliação</option>
                        {% for avaliacao in avaliacoes %}
                            <option value="{{ avaliacao.id }}">{{ avaliacao.descricao }}</option>
                        {% endfor %}
                    </select>                        
                    <input type="submit" class="btn-cadastro mt-10" value="Avaliar">
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
    <script>

        const container = document.getElementById('pdf-container');

        pdfjsLib.getDocument("{{apostila.arquivo.url}}").promise.then(pdf => {
            pdf.getPage(1).then(page => {
                const canvas = document.createElement('canvas');
                const context = canvas.getContext('2d');
                const viewport = page.getViewport({ scale: 0.6 });

                canvas.width = viewport.width;
                canvas.height = viewport.height;

                page.render({ canvasContext: context, viewport }).promise.then(() => {
                    container.appendChild(canvas);
                });
            });
        });
    </script>
{% endblock 'conteudo' %}